steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'download']
    env: ['PROJECT_ROOT=webapp', 'GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', 'webapp', '-v']
    env: ['PROJECT_ROOT=webapp']
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=webapp']
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', 'webapp']
    env: ['PROJECT_ROOT=webapp']
artifacts:
  objects:
    location: 'gs://vfoucault-targetrepo/'
    paths: ['awesome-webapp']