steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'download']
    env: ['PROJECT_ROOT=github.com/vfoucault/awesome-webapp', 'GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v']
    env: ['PROJECT_ROOT=github.com/vfoucault/awesome-webapp']
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=github.com/vfoucault/awesome-webapp']
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', 'main']
    env: ['PROJECT_ROOT=github.com/vfoucault/awesome-webapp']
artifacts:
  objects:
    location: 'gs://vfoucault-targetrepo/'
    paths: ['awesome-webapp']